//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Xnlab.SQLMon.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    var temp = new ResourceManager("Xnlab.SQLMon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static Bitmap Accelerator2 {
            get {
                var obj = ResourceManager.GetObject("Accelerator2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap Cross2 {
            get {
                var obj = ResourceManager.GetObject("Cross2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap Edit2 {
            get {
                var obj = ResourceManager.GetObject("Edit2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap Gear2 {
            get {
                var obj = ResourceManager.GetObject("Gear2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap History2 {
            get {
                var obj = ResourceManager.GetObject("History2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap List2 {
            get {
                var obj = ResourceManager.GetObject("List2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap New2 {
            get {
                var obj = ResourceManager.GetObject("New2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap Proxy2 {
            get {
                var obj = ResourceManager.GetObject("Proxy2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap Refresh2 {
            get {
                var obj = ResourceManager.GetObject("Refresh2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap Schedule2 {
            get {
                var obj = ResourceManager.GetObject("Schedule2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap Server {
            get {
                var obj = ResourceManager.GetObject("Server", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap Server2 {
            get {
                var obj = ResourceManager.GetObject("Server2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap Table2 {
            get {
                var obj = ResourceManager.GetObject("Table2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
